version: 2

defaults: &defaults
  docker:
    - image: circleci/node:10
  working_directory: ~/react-native-paper

jobs:
  install-dependencies:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/react-native-paper
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            - dependencies-
      - restore_cache:
          keys:
            - dependencies-docs-{{ checksum "docs/package.json" }}
            - dependencies-docs-
      - restore_cache:
          keys:
            - dependencies-example-{{ checksum "example/package.json" }}
            - dependencies-example-
      - run: |
          yarn install --cwd example --frozen-lockfile
          yarn install --cwd docs --frozen-lockfile
          yarn install --frozen-lockfile
      - save_cache:
          key: dependencies-{{ checksum "package.json" }}
          paths: node_modules
      - save_cache:
          key: dependencies-docs-{{ checksum "docs/package.json" }}
          paths: docs/node_modules
      - save_cache:
          key: dependencies-example-{{ checksum "example/package.json" }}
          paths: example/node_modules
      - persist_to_workspace:
          root: .
          paths: .
  lint:
      <<: *defaults
      steps:
        - attach_workspace:
            at: ~/react-native-paper
        - run: |
            yarn lint
  typescript:
      <<: *defaults
      steps:
        - attach_workspace:
            at: ~/react-native-paper
        - run: yarn typescript
  build-package:
      <<: *defaults
      steps:
        - attach_workspace:
            at: ~/react-native-paper
        - run: yarn prepare
  unit-tests:
      <<: *defaults
      steps:
        - attach_workspace:
            at: ~/react-native-paper
        - restore_cache:
            name: Restoring Jest Cache
            keys:
            - jest-cache-{{ .Branch }}
            - jest-cache
        - run: yarn test --maxWorkers=2 --coverage
        - store_artifacts:
            path: coverage
            destination: coverage
        - save_cache:
            paths:
            - ./cache/jest
            key: jest-cache-{{ .Branch }}
  build-docs:
      <<: *defaults
      steps:
        - attach_workspace:
            at: ~/react-native-paper
        - run: |
            cd docs && yarn build && cd ..
            bash .circleci/comment-artifacts.sh
        - store_artifacts:
            path: docs/dist
            destination: docs
  deploy-docs:
      <<: *defaults
      steps:
        - checkout
        - attach_workspace:
            at: ~/react-native-paper
        - add_ssh_keys:
            fingerprints:
              - "2f:b4:ed:e1:25:88:5c:4a:03:c2:16:40:56:70:29:29"
        - run: |
            bash .circleci/deploy-docs.sh

workflows:
  version: 2
  build-and-test:
    jobs:
      - install-dependencies
      - lint:
          requires:
            - install-dependencies
      - typescript:
          requires:
            - install-dependencies
      - unit-tests:
          requires:
            - install-dependencies
      - build-package:
          requires:
            - install-dependencies
      - build-docs:
          requires:
            - install-dependencies
          filters:
            branches:
              ignore: master
      - deploy-docs:
          filters:
            branches:
              only: master
